---
title: "symbolicMatrix"
output: 
    pdf_document:
        extra_dependencies: ["amsmath"]
date: "2024-08-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(matlib)

#' @param label character vector specifying the LaTeX label to use (e.g., \code{eqn:myeqn})
#' @param 
#' @examples 
#' Eqn(cat('y=mc^2'))
#' Eqn(cat('y=mc^2'), number = FALSE)
#' Eqn(cat('y=mc^2'), label = 'eqn:einstein')


Eqn <- function(..., number = TRUE, label = NULL) {
    wrap <- if(number) "equation" else "equation*"
    cat(sprintf("\n\\begin{%s}\n", wrap))
    if(!is.null(label)) 
        cat(sprintf('\\label{%s}\n', label))
    eval(...)
    cat(sprintf("\\end{%s}\n", wrap))
}
```

```{r results='asis', echo=FALSE}
Eqn(cat("X=U \\lambda V"), label='eqn:svd')
Eqn({
    symbolicMatrix("u", "n", "k", lhs = '')
    symbolicMatrix("\\lambda", "k", "k", diag=TRUE)
    symbolicMatrix("v", "k", "p", transpose = TRUE)
})
```

As seen in Equation \ref{eqn:svd} \ldots

## matrix2latex

```{r}
A <- matrix(paste0('a_', 1:9), 3, 3)
b <- paste0("\\beta_", 1:3)
```

```{r}
matrix2latex(cbind(A,b))
```

```{r results='asis', echo=FALSE}
matrix2latex(cbind(A,b)) |> Eqn(number=FALSE)
```





